log:
  level: INFO

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        options: default

providers:
  file:
    filename: "/etc/traefik/dynamic-config.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@deputatai.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
