version: '3.9'

services:
  imperium-backend:
    build:
      context: ../imperium-backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  imperium-hub-app:
    build:
      context: ../imperium-hub-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  hermes-workspace:
    build:
      context: ../hermes-workspace
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  react-playground:
    build:
      context: ../react-playground
      dockerfile: Dockerfile
    ports:
      - "3002:3000"

  hermes-agent:
    build:
      context: ./ml-tools
      dockerfile: Dockerfile
   ports:
      - "8001:8001"

